### ISSUE TITLE
Correct use of parentheses RPQ

### ISSUE THREAD

**Issue by rgarcias** [ldbc/gcore-spark#32]
For some RPQ expression using  parentheses, the query crashes.

**To Reproduce**
1. Open the console
2. Run a query like this:  CONSTRUCT (n)-/@p:reach/->(m) MATCH (n)-/p<(:HasInterest |:IsLocatedIn)! :Knows>/->(m)
3. Error: "Key not found"

**Expected behavior**
A successful query execution.

**Comment by renzoar** [comment]
In order to improve and simplify the syntax of RPQs, with respect to parentheses, we are going to modify the current grammar with the following one:
PathExpression = “<” ComplexPE “>”
ComplexPE = “(” ComplexPE ComplexPE “)”
ComplexPE = “(” ComplexPE “|” ComplexPE “)”
ComplexPE = “(“ ComplexPE “)”  “+”
ComplexPE = “(“ ComplexPE “)”  “*”
ComplexPE = “(” ComplexPE “)”  “?”
ComplexPE = AtomicPE
AtomicPE = Label
AtomicPE =Label “!”
AtomicPE = Label “^”
AtomicPE = “_”

Note that the current grammar allows an atomic path expression with multiple labels (e.g. "a : b : c"). We are going to remove this feature as we have alternation (union) of path expression (e.g. "a | b").

**Comment by ramhgarcias** [comment]
The error was in the edges of the example graph.

**Comment by ramhgarcias** [comment]
fixed by https://github.com/ldbc/gcore-spark/commit/0976e9d86aa61192579e8fce59d37d679e35bcdc
